### ISSUE TITLE
The destructible objects aren't "Destructible!!! " The scripts slows down the game 100x times !

### ISSUE THREAD

**Issue by Abdelrahmanamhawy** [sabikku/unity-sprite-cutter#1]
The sliced objects aren't destroyed and they just keep on being created more and the game is slowed down 100x,it's being slower than a ps1 game !!!! It's a shame that with this good design and idea you screwed it up on this small bug that ruins everything !!!! It's terrible .

**Comment by sabikku** [comment]
Hmm.

If you use slicing, you don't want to _always_ destroy the sliced-off part. That's why it doesn't work automatically.

While slicing, you get the sliced GameObject back, so you can manage it yourself. For example, you can create following MonoBehaviour:
```
using UnityEngine;
	
public class DestroyAfter : MonoBehaviour {
	public float delay = 1f;
	float endTime;
	void Start() {
		endTime = Time.time + delay;
	}
	void Update() {
		if ( Time.time > endTime ) {
			GameObject.Destroy( gameObject );
		}
	}
}
```

Then, after cutting, just add the component to sliced gameObject:
```
var result = SpriteCutter.Cut( ... );
var d = result.secondSideGameObject.AddComponent<DestroyAfter>();
d.delay = 5f;
```

**Comment by Abdelrahmanamhawy** [comment]
Thank you for responding so fast,and sorry if i seemed rude..it's just that the laptop frozen when i was trying the game.
in var result=spritecutter.cut()..i don't put anything in this argument?
also are those two different scripts?
last question,i attach the first one for the sprite and the second for the sprite or the two for different game objects??

**Comment by sabikku** [comment]
For the argument, choose whatever you have in your current code, and yeah, those are two different scripts.

I think I cannot help you more.

**Comment by Abdelrahmanamhawy** [comment]
What do you mean whatever i have?????? Look i am not stupid okay ...if i tried to write the second script in scriptcutter it will automatically generate a stackoverflow problem which will freeze the whole game...what argument are you talking about ?? The argument cut method takes is spritecutterinput....but where do i write it ?? in the spritecutter script to make a stackoverflow error or write a new script or what exacly ? You aren't clear enough ! Where do i write this piece of code (the 2nd one) and the argument it takes is important and it's isn't that clear believe me ...

**Comment by Abdelrahmanamhawy** [comment]
How to know which gameobject should i assign it to spritecutterinput and make it an object? I can't make it the main gameobjext like the box for example.Dude if you didn't want this kind of question then you should have made it easier for people to use it without having to keep searching and diving in your source code.

**Comment by Abdelrahmanamhawy** [comment]
How in earth should i identify the sliced game object??? Do you think is something that any user can do it ???? Anyone who is just using this package or asset can identify the sliced gameobject eaisly? I doubt man

**Comment by sabikku** [comment]
The first thing you should do is learning C#. Then, go through Unity Learn tutorials line. At last, read the _unity-sprite-cutter/Assets/UnitySpriteCutterExample/_ examples, especially _LinecastCutterBehaviour_. When you're ready, study the source code to understand how it works.

Hope it helps.
